spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


application:
  jwt:
    secret-key: superdupersecuredkeyforthisapplication
    token-prefix: "Bearer "
    token-expiration-after-days: 10
